### ISSUE TITLE
Favorites aren't completely pulling

### ISSUE THREAD

**Issue by KaptainKid** [NerdNumber9/TachiyomiEH#10]
Hi, thanks for the great app!

I'm trying to pull my favorites from ex-hentai but only some are coming over. Was wondering whether I was doing something wrong. I tried logging out and back in as well as updating TachiyomiEH

Thanks a bunch!

**Comment by NerdNumber9** [comment]
I will hopefully fix this by the next release. I don't think I will be able to release this week however as I am currently studying for exams.

**Comment by KaptainKid** [comment]
No worries! Just wanted to post in case it wasn't something you were aware
of. Thanks a bunch, good luck on exams :)

**Comment by NerdNumber9** [comment]
The favorites downloader has been replaced with a sync mechanism in the latest release (v6.8.0). It *should* be more stable.

Note that the downloader now behaves like a sync mechanism so it will also upload your local favorites to ExHentai's servers. You can disable this behavior (and turn it back into a 'download only' mechanism) in the 'E-Hentai' settings page.
