### ISSUE TITLE
Latest Version Problem

### ISSUE THREAD

**Issue by ichijoraku** [NerdNumber9/TachiyomiEH#11]
I'm currently having problem accessing Kissmanga. I need the latest version to avoid Http Error #503. 
I tried to download it but it always says app invalid or download unsuccessful. I tried to use other browser but still I can't download the app.

**Comment by NerdNumber9** [comment]
I will fix this in the next release. I don't think I will be able to release this week however as I am currently studying for exams.

**Comment by ichijoraku** [comment]
hahaha.. ok. I understand. Even for me. School first for the future. tnx for noticing anyway. I'll wait it.

**Comment by NerdNumber9** [comment]
@ichijoraku This *should* be fixed in the latest release (v6.8.0). Please re-open this issue if it isn't and I will take a closer look into it.
