### ISSUE TITLE
Download problem.

### ISSUE THREAD

**Issue by ichijoraku** [NerdNumber9/TachiyomiEH#12]
I can't still download the app. Either invalid link or download failed.

**Comment by NerdNumber9** [comment]
Can you download it from this link? https://github.com/NerdNumber9/TachiyomiEH/releases/download/v6.8.0-EH/app.apk

**Comment by ichijoraku** [comment]
Download app.apk failed. Please try agian. I was using default browser, opera mini old and latest and UC browser.

**Comment by ichijoraku** [comment]
I even used android IDM ... 
Is it because of the link ? I tried to download the regular tachiyomi and I successfully downloaded it.

**Comment by ichijoraku** [comment]
Download successful. I used pc. probably my phone was the problem..

**Comment by NerdNumber9** [comment]
Hmm, not sure what the problem is here. I assume you have this all sorted out so I will close this issue now.
