### ISSUE TITLE
[Minor] Sentence typo in sync dialog

### ISSUE THREAD

**Issue by Yandols** [NerdNumber9/TachiyomiEH#13]
There is a small typo or grammatical error in the sync dialog.

It currently reads: 

> Sync is currently throttling and may take a long to complete.

It should be: 

> Sync is currently throttling and may take a long **_time_** to complete.

Specifically i mean this dialog:

![screenshot_20180203-173040](https://user-images.githubusercontent.com/2742965/35766352-b3988caa-0911-11e8-98f3-d7a9a34ec09a.png)

**Comment by NerdNumber9** [comment]
Oops... Thanks for the head up, I'll fix this in the next release.

**Comment by NerdNumber9** [comment]
Fixed in the latest release.
