### ISSUE TITLE
Ignore deleted galleries while syncing with ExH

### ISSUE THREAD

**Issue by Yandols** [NerdNumber9/TachiyomiEH#14]
I wanted to use the new functionality to sync with ExH after it was added in 6.8.0-EH. However it stopped halfway after an error stating that a gallery it was trying to sync has been deleted. It then aborted the sync process entirely.

My suggestion is to either add a button to ignore said error and allow continue the sync process or to ignore it entirely while logging it in an error log that can be seen in the settings or something.

The Error in question: 

![screenshot_20180203-173144](https://user-images.githubusercontent.com/2742965/35766441-b58fdec6-0913-11e8-9a54-f3bc0cb9305c.png)

**Comment by NerdNumber9** [comment]
This is actually kinda funny. The original plan was to have the app ignore errors and continue on syncing. It would report all the errors when the sync finished. I changed this at the last minute however, as this could cause deleted galleries to just mysteriously disappear (although I guess it doesn't really matter, they are *deleted* galleries after all).

In the next release, I will ask the user about whether or not they want to continue the sync if an error crops up.

**Comment by NerdNumber9** [comment]
Fixed in latest release. It's an option in the settings section.
