### ISSUE TITLE
ExHentai links

### ISSUE THREAD

**Issue by SyntacticSyntax** [NerdNumber9/TachiyomiEH#15]
I'm getting problems with ExHentai links. It gives me this error first when I reset the app cache then on consecutive links it just says loading then throw me back to where I was.
![screenshot_20180207-192225](https://user-images.githubusercontent.com/11613586/35914435-3bf9524e-0c3e-11e8-9913-45fe61bc1cae.png)

**Comment by NerdNumber9** [comment]
Can you try this version of the app?: https://file.quad.moe/app-dev-debug.apk

Note that it will install alongside the current version of the app so you don't have to worry about losing data.

**Comment by SyntacticSyntax** [comment]
Still doesn't work on that app. Same error appears.

**Comment by NerdNumber9** [comment]
Duplicate of #16
