### ISSUE TITLE
Exhentai Galleries Blank Page

### ISSUE THREAD

**Issue by migstergames** [NerdNumber9/TachiyomiEH#16]
When I open Exhentai in Gallery's, Both Latest and Browse just shows blank page or No Results Found. Did  re-enable, recheck and login Exhentai many times. When I Clear cookies and chapter cache it does show the galleries, but when opening a file, it will say Page list is empty.

**Comment by NerdNumber9** [comment]
Alright, I need a little bit more information on this subject to find the problem:
1. Did this happen after you upgraded to the latest app version?
    1. If so, did you get asked to 'Migrate library metadata' after the update?
          1. Did you migrate the metadata or did you leave it for later?
2. Can you check if you are temporarily banned on ExHentai? Visit ExHentai in your browser.

**Comment by migstergames** [comment]
1. The version it happened is v6.6.0. So then updating to the latest release, thinking maybe because it is 
    outdated, but still doesn't work. Updated it through settings>about.
           i. No, it didn't asked me 'Migrate library metadata'. It only showed me updated Highlights.
                     a. The downloaded files still there, and can still 
                         be viewed and opened.
2. My account seems fine (there's no notification on profile or any indication that me being banned) and I can view Exhentai in browser in both computer and mobile chrome normally. E-hentai and nhentai works alright in tachiyomieh, just only Exhentai that has this problem

**Comment by Kaijyu** [comment]
I decided to do a test. I uninstalled TachiyomiEH and tried previous version of the app. v6.6.0 and v6.1.4 etc, it seems no matter which version I use the same problem happens. black screen when trying to go to latest or browse. Weird to say but when I went to advanced setting in the app and clear cookies. I tried again it technically worked. I could browse but when I went to chapters "Page List Is Empty" ( even if I tried downloading same thing happens) 
![screenshot_20180210-140512](https://user-images.githubusercontent.com/36341641/36066319-edf19b1a-0eea-11e8-9c09-709d0b81fc08.png)
then after I do that and go to check another manga the problem happens again blank screen
![screenshot_20180210-140626](https://user-images.githubusercontent.com/36341641/36066322-f5306852-0eea-11e8-973d-5bb6f336a19c.png)

**Comment by NerdNumber9** [comment]
Thanks for the information. It looks like something changed on ExHentai's side. I'll try to figure out what's going on today.

**Comment by NerdNumber9** [comment]
Alright, I've pinned down the issue. It almost certainly has to do with the recent update to the ExHentai/E-Hentai website (although I'm not sure why E-Hentai still works): https://forums.e-hentai.org/index.php?showtopic=213374

I'll try to roll out a fix before Wednesday.

**Comment by NerdNumber9** [comment]
This should now be fixed in the latest release.
