### ISSUE TITLE
Fav Sync not Working

### ISSUE THREAD

**Issue by korg34** [NerdNumber9/TachiyomiEH#18]
Using v6.8.1-EH
the "Sync favorites" is only pulling the categories from exh not the favorites but it says "Sync complete"
reinstall didnt fix

**Comment by null-dev** [comment]
I am actually aware of this issue (discovered it just after release). It will be fixed tonight.

**Comment by NerdNumber9** [comment]
I am actually aware of this issue (I discovered after release). It will be fixed tonight.

**Comment by NerdNumber9** [comment]
Actually I will have to get to this tomorrow, I want to get some more testing done so this doesn't happen again.

**Comment by NerdNumber9** [comment]
This *should* be fixed in v6.8.2 now but I can't properly test the fix as I have too much favorites :(.
