### ISSUE TITLE
Batoto is not working

### ISSUE THREAD

**Issue by XeiXion** [NerdNumber9/TachiyomiEH#2]
Version: v5.0.3-EH

The Batoto source does not seem to be working. It works on the Tachiyomi app but is not working on the TachiyomiEH app

**Comment by Sorcerian-Bootleg** [comment]
Same here. v5.0.3-EH

Logged in with my Batoto account, but galleries won't show up.

I see that TachiyomiEH's last update was 3 months ago while Tachiyomi's main branch is updated 10 days ago. Is this branch abandoned, or are you merging it with the main branch?

**Comment by NerdNumber9** [comment]
Fixed in latest release. Sorry for the delay!
