### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by ichijoraku** [NerdNumber9/TachiyomiEH#22]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**
6.8.0

**Issue/Request:**

error when downloading manga.
(Syntax error: Parse error(line 1).. this error)

**Comment by NerdNumber9** [comment]
What source is this?

**Comment by ichijoraku** [comment]
kissanime. I can view the manga but error in download.

**Comment by ichijoraku** [comment]
it probably happened when I hid all sources except kissanime.

**Comment by ichijoraku** [comment]
its ok now. just a bug... probably.

**Comment by NerdNumber9** [comment]
Should be fixed in latest release
