### ISSUE TITLE
App won't start after the new update.

### ISSUE THREAD

**Issue by Yandols** [NerdNumber9/TachiyomiEH#31]
I saw there was a new update today, so I updated it. However after doing so the app now refuses to start. I tried restarting my phone but that doesn't make any difference. I can no longer start the app at all, it just goes to a white screen for no more than half a second and crashes back to the home screen. There's nothing I can do. I was thinking of downgrading back to 7.0.0 but android doesn't allow that.

**App version:** 7.2.0

**Other details:**
Phone: OnePlus Two A2003
Android Version: 6.0.1

**Comment by immoempe2** [comment]
Same problem
Phone: LG G3 Stylus
Android version: 5.0.2

**Comment by NerdNumber9** [comment]
Alright, can you guys try this APK to see if it still crashes? ~~https://1fichier.com/?y9rdk33wue~~

**Comment by Yandols** [comment]
Unfortunately my phone won't even let me install that one for some reason. It says "App not installed" after trying to install it.

**Comment by NerdNumber9** [comment]
Alright, sorry about this mess, does this new APK work? https://1fichier.com/?qi7sjsdinf

**Comment by Yandols** [comment]
Well that one installed but the app still refuses to start. :(

**Comment by NerdNumber9** [comment]
Alright, thanks. Looks like the only way I'll be able to figure this out is if I get some logs. It would be awesome if you could follow the steps below to get them:

Steps for taking logs:

1. Open TachiyomiEH (which will cause the crash).
2. Immediately after the crash occurs, go to the `Settings` app on your phone, tap on `Developer options` and then tap on `Take bug report`. If you can't find the `Developer options` section, please refer to this article on how to enable it: https://www.digitaltrends.com/mobile/how-to-get-developer-options-on-android/
3. If asked about the type of bug report, choose `Interactive report`.
4. Open the notification shade and wait for the bug report to complete. Once finished, tap on the notification to send the bug report. You can email it to me at nerd.number9@yandex.com or upload it to Google Drive and post the link here.

Thanks!

**Comment by Yandols** [comment]
I've just done that after a fresh reboot and sent it over to your email. Hopefully it will be able to help.

**Comment by NerdNumber9** [comment]
Alright, I think I've pinned down the issue from your logs (thank you!). Can you see if this APK works? https://1fichier.com/?lxnodnkha7

**Comment by vicho1820** [comment]
I am having the same problems, it seems that I can't make a bug report of it.
I am using an honor4x with Android 4.4.2, and EMUI 3.0.

**Comment by immoempe2** [comment]
The last apk is working now, thanks a lot!

**Comment by Yandols** [comment]
Can confirm in the latest apk the app finally works again. Thank you so much!

**Comment by ichijoraku** [comment]
Is it safe to install that apk ? Im using Android 4.2.2..

**Comment by ichijoraku** [comment]
what version. is that apk fro. the last link .?

**Comment by NerdNumber9** [comment]
@ichijoraku The APK is version v7.2.2 but I never uploaded it as an official release as I wanted someone to test it to make sure it worked. I've uploaded it as an official release now here: https://github.com/NerdNumber9/TachiyomiEH/releases/tag/v7.2.2-EH
