### ISSUE TITLE
App is still crashing, in Android 4.4.2, after updating to 7.2.2

### ISSUE THREAD

**Issue by vicho1820** [NerdNumber9/TachiyomiEH#32]
App version: 7.2.2

Issue/Request: The app crashes upon opening

I am using an Honor 4x with Android 4.4.2, EMUI 3.0, I don't seem to be able to create a bug report

**Comment by NerdNumber9** [comment]
Do you know if you have the app lock enabled?

**Comment by vicho1820** [comment]
It wasn't enabled. 
Something weird happens when it is enabled, I open the app, it crashes, but when I enter the code, the app start working partially, allowing me to read the mangas that were in the library, then crashes when you load the homepage.

Here are some screenshots, because I can't make a bug report.
https://drive.google.com/folderview?id=1vOdHTJDjPfn6Y4yidxgpL5xH8G_y3wuk

**Comment by vicho1820** [comment]
There are missing parts in the layout of the homepage, as seen in the screenshot

**Comment by NerdNumber9** [comment]
Alright, can you see if this APK works for you? https://1fichier.com/?51lxhos8zd

**Comment by vicho1820** [comment]
It worked.

**Comment by NerdNumber9** [comment]
Wow, ok perfect! No idea what happened though, I literally just fixed with bugs in the app lock...

I'll push this out as an official release to the other users in a couple minutes.

**Comment by Reshiban** [comment]
Hello, the 4.2.2 version (of Android) crash even with the last Update, can you check please? :D

**Comment by vicho1820** [comment]
I changed my phone, I don't have 4.4.2 anymore. I am sorry for not being of
any help.
