### ISSUE TITLE
Outside Links Not Working

### ISSUE THREAD

**Issue by ReworkedBrain** [NerdNumber9/TachiyomiEH#38]
**App version:**
v7.4.2-EH
**Issue/Request:**
After clicking a link from E-Hentai, ExHentai, nHentai, etc., I'm asked if I want to open it via TachiyomiEH or Chrome. After selecting TachiyomiEH, it simply doesn't load the link. TachiyomiEH will open, but after a second or two of showing a spinning circle, it will close itself. When will this be fixed? Thanks for listening!
**Steps to reproduce (if applicable)**

 1.
 2.   N/A
 3.

**Other details:**
N/A

**Comment by NerdNumber9** [comment]
I'll look into this, thanks for the report!

**Comment by NerdNumber9** [comment]
Alright, I've tried fixing this in today's release. I'm not sure if the fix works however, so please update me on that once you try it out.

Also, I'm not sure if you are aware of this (it's existed for a while) but as a workaround, you can actually paste a gallery link in the search bar of a source in TachiyomiEH and it will find the gallery that corresponds to that link.

**Comment by ReworkedBrain** [comment]
Oh really? I didn't know you could do that! If I knew that, I probably
wouldn't have told you about the glitch, lol

Thanks for looking into it, my man

**Comment by ReworkedBrain** [comment]
Upon clicking an ExHentai link, this shows up. Maybe it's just me... Either
way, thanks for giving it attention.

**Comment by ReworkedBrain** [comment]
It's fixed! Thanks for giving it attention homie
