### ISSUE TITLE
Mangasee

### ISSUE THREAD

**Issue by bvalerioh** [NerdNumber9/TachiyomiEH#50]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**
7.4.4
**Issue/Request:**
Mangasee.net da error de que no existe el dominio, no se si lo cambiaron a mangasee.us que es el que se puede encontrar
**Steps to reproduce (if applicable)**

 1.ir al la galería mangasee
 2.escoger cualquier manga
 3.abrir un capítulo

**Other details:**
Sería todo

**Comment by NerdNumber9** [comment]
Use the extension.
