### ISSUE TITLE
nhentai 404

### ISSUE THREAD

**Issue by lupangvirgo** [NerdNumber9/TachiyomiEH#53]
**App version:**
7.4.4-EH

**Issue/Request:**
source : nhentai
HTTP error 404

**Steps to reproduce (if applicable)**
this issue start around 24hrs ago. it 404 everytime I browse nhentai.
manga in my library is fine but after I clear cache and cookies, manga in my library also 404 except for those downloaded

**Other details:**
I try open "https://nhentai.net/" in web browser but I can still open it
try again with "nhentai.net/" but this one cannot open

**Comment by woeijiunn88** [comment]
https://github.com/NHMoeDev/NHentai-android/issues/108#issuecomment-454054060

**Comment by lupangvirgo** [comment]
that's sad. E-hentai is absolutely a good site but have a lot of forbidden content.
I hope that nhentai will unlock API in the far future.

**Comment by az4521** [comment]
i've fixed nh in my fork
https://github.com/az4521/Tachiyomi

**Comment by NerdNumber9** [comment]
Fixed in latest release.
