### ISSUE TITLE
App forcibly shut down / crashed when loading gallery from hitomi.la

### ISSUE THREAD

**Issue by dionisiusAw** [NerdNumber9/TachiyomiEH#54]
**App version:** 7.4.4-EH

**Issue/Request:** APP crashed whenever I try to load hitomi.la

**Steps to reproduce (if applicable)**

 1. Open TachiyomiEH
 2. Go to Galleries
 3. Click on Hitomi.la (very slow search)
 4. Wait a few seconds..
 5. Crashed.

**Other details:**
I'm not sure if this situation a general issue or only happening to me. Does it have any connection with the very slow search? Since it took more resources to load hitomi.la than other sources and my android can't withstand it?

**Need help/response.** I don't know what to do and for the mean time, I am using other H sources (which work perfectly fine).

**Comment by ronalhvaldez** [comment]
Its happening to me too

**Comment by BinariGuy** [comment]
Same here

**Comment by NerdNumber9** [comment]
Fixed in latest release.
