### ISSUE TITLE
App forcibly shut down or crashed when opening or clicking tag from info page in exhentai

### ISSUE THREAD

**Issue by RatchetNine76** [NerdNumber9/TachiyomiEH#55]
App version: 7.4.4

Issue: app forcibly shutdown or crash when click a tag in any gallery/manga info tab, both from catalogue or downloaded

Steps to reproduce (if applicable)

 1.Browse in Exhentai
 2.Open any gallery/manga
 3.In info tab, at the bottom open any tags, when opens in global results it immediately crashes

Other details: Just bought the new Galaxy s10 plus because my old phone broke a week ago. when I try open a tag it immediately crashes

**Comment by ronalhvaldez** [comment]
Do you have hitomi enabled? Bc thats would be what make it crash

**Comment by RatchetNine76** [comment]
I just turned if off, it works now. Thanks for the help
