### ISSUE TITLE
E-(x)hentai redesign - browse and latest no longer work.

### ISSUE THREAD

**Issue by Solipso** [NerdNumber9/TachiyomiEH#56]
**App version:**
7.4.4-EH
**Issue/Request:**
E-hentai (and fjords) have undergone a redesign, maybe changing how their main page works. Now Tachiyomi can no longer see galleries on these pages, so "Browse" and "Latest" show "No results found".

**Comment by Solipso** [comment]
One new error caused by redesign - it seems like the app sees newly added galleries (by opening them as links on browser or batch adding), but is missing their thumbnails.

**Comment by Zero777X** [comment]
I am having issues as well with EHentai and EXHentai. "No results found" is my error text on the bottom of the screen. However, old titles are still viewable.

**Comment by hparadiz** [comment]
Bumping this as well. Whole app is basically broken.

**Comment by Cube-Chan** [comment]
Yup. Whole bunch of other sites also don't work anymore.

**Comment by LakotaGray** [comment]
You can still add new titles from the site in app by using the add batch galleries. You’ll just need to URL of the title, but it will then add properly and be able to be downloaded or viewed.

**Comment by smokeofc** [comment]
Syncing favorites seems to mostly remove all e-hentai titles from the library. Love this app and really hoping a fix is en route :)

**Comment by yalopov** [comment]
Bois we need to fix this ASAP.

Where can we start looking at?

**Comment by Solipso** [comment]
Well, considering that developer of this fork @NerdNumber9 was never online since august 2018 (at least to my knowledge), we can safely say that this project is dead.

That leaves us with few options:

1) We stay still and hope that @NerdNumber9 returns and fixes this (and all other) issues.

2) We go to @Inorichi and ask him to merge this fork or at least add local sources as extensions and to maintain e*hentai, tsumino, hentai cafe and hitomi with his team.

3) Someone else with knowledge of Kotlin and Java creates his own fork and begins to maintain this app.

**Comment by Scrxtchy** [comment]
Is anyone working on this already or should I take a look when I find the time?

**Comment by Solipso** [comment]
@Scrxtchy It would be the best if you took a look.

**Comment by Scrxtchy** [comment]
Better pop android studio back on this bitch then 😎

**Comment by ghost** [comment]
I created a temporary stopgap fix which re-enables searching and browsing of ehentai and the fjords. Favorites are broken though, I recommend disabling favorites syncing. I did this for myself / it's not very well tested, backup all your app data, etc etc:

Diff: https://github.com/ilwaz/TachiyomiEH/commit/0fac958e56bacba1c4b234f52474ed84a29d91f1
Release: https://github.com/ilwaz/TachiyomiEH/releases/tag/v7.4.5-EH

In terms of future steps, there have been some large changes to Tachiyomi recently, so getting us back to parity with source might be a bit of work. Unfortunately I won't be able to take that on for some time, so it might be best for someone else to attempt it.

**Comment by Scrxtchy** [comment]
I've pulled this commit into my own repo. I'm going to spend some time later to see how much we can do in terms of getting website scraping back up and running for the sites it does not work with.
After that is gauged, if we can fix some with little effort, that could be done, but at some point the features from the main reader should be merged which may help with any further developments

**Comment by Scrxtchy** [comment]
Man can't even build this shit due to crashlystics lmao

**Comment by ghost** [comment]
@Scrxtchy, here's what I did:
1) Signup at fabric.io
2) Grab the api key from https://fabric.io/kits/android/crashlytics/install which they say to add to `AndroidManifest.xml` (but do not add it there).
3) Create `app/fabric.properties` with the contents `apiKey={apk_key_value}`

That fixed things for me.

Note: Crashlytics eventually moved to Firebase (which is owned and run by Google). Tachiyomi EH is on the old Crashlytics which needs a Fabric.io account. Tachiyomi itself has upgraded the the Firebase one though from what I can tell.

**Comment by Solipso** [comment]
Tried out @ilwaz's app. Both e*hentai online.

Remaining bugs from overhaul are favourites sync as mentioned earlier and few thumbnails not appearing normally in "Latest" and "Browse".

If you go to their info they show up normally though.

**Comment by RX14** [comment]
You can fix the crashlitics build error more easily by just commenting out `apply plugin: 'io.fabric'` in `app/build.gradle`

**Comment by RX14** [comment]
For reference, here's @NerdNumber9 on why tachiyomi-eh isn't a tachiyomi plugin: https://github.com/inorichi/tachiyomi-extensions/issues/94#issuecomment-325027557. This is at least useful as a guide on what needs to be ported to a plugin.

**Comment by Scrxtchy** [comment]
> You can fix the crashlitics build error more easily by just commenting out `apply plugin: 'io.fabric'` in `app/build.gradle`

I did try this, but I think this caused some compiling errors in the kotlin files, issuing an API key fixed the error

**Comment by Scrxtchy** [comment]
I'm currently working on fixing the favourites parser that was marked as TODO by ilwaz
https://github.com/Scrxtchy/TachiyomiEH/commit/0fac958e56bacba1c4b234f52474ed84a29d91f1#diff-38623e27ff84b67842f6dafccd22ab42R67

My build times are roughly 10-25 minutes

**Comment by kadaikhan** [comment]
Tried the @ilwaz 's app. It crashes when tapping the artist's name to start a search of that artist.

**Comment by Scrxtchy** [comment]
Thanks, also getting that on my end

**Comment by Solipso** [comment]
@kadaikhan Did you switch off hitomi source? It was causing crash since february.

Edit: No crash here. Hitomi disabled.

**Comment by kadaikhan** [comment]
@Solipso I didn't know about that.
I did switch it off as you recommended and it seems that everything is ok for now, thank you.
Would use more the @ilwaz 's app to see if I find another problem and post it here if I do.
I just wish I knew how to program to help with this.

**Comment by Solipso** [comment]
@kadaikhan Sure! But before writing about it here, check local issues first. Some of them have solutions or bypasses.

**Comment by RX14** [comment]
> I did try this, but I think this caused some compiling errors in the kotlin files, issuing an API key fixed the error

Try using the `assembleFdroidDebug` task after removing the fabric plugin. Builds much faster.

**Comment by Scrxtchy** [comment]
Is this the punishment I get for using gradle-aware make?
![image](https://user-images.githubusercontent.com/12771982/54866007-eb688300-4dc2-11e9-81ad-732aa3a102af.png)

**Comment by Scrxtchy** [comment]
I've jumped through so many hoops for gradle today, spend seven hours fixing gradle and an hour programming. Classic

https://github.com/Scrxtchy/TachiyomiEH/commit/17ca4f185fe0b7f07a7f8d6de2cb4c0ba973d41d

Still working this out, Since I have no idea how exh used to handle styling of favourites, I've just attempted some things with it.
(while writing this, I'm assuming this may be an image offset, did they use to use the diamonds?)

Now they're using border colours around the timestamp, so it's actually pretty hard. 
Like the simplest solution would be a regex, but they actually allow you to rename favourites
![image](https://user-images.githubusercontent.com/12771982/54868385-0c8b9c80-4de0-11e9-8261-3f7a5a920c2d.png)

![image](https://user-images.githubusercontent.com/12771982/54868419-54aabf00-4de0-11e9-9374-b85f09330cf0.png)

This unholy code better be worth it in the end, because getting this shit to a 0-10 scale is not going to be pretty

**Comment by Scrxtchy** [comment]
that wasn't too bad
![image](https://user-images.githubusercontent.com/12771982/54868625-82910300-4de2-11e9-90fa-8b45edf79eec.png)

Might need someone else to build this shit because I'd rather not make another deal with the devil and lose sleep over gradle fuckery
https://github.com/Scrxtchy/TachiyomiEH/commit/7b781b8f9d8d29c8c0d1767218babf685b36f8ee

**Comment by joseph619** [comment]
@Scrxtchy Don't give up bro, we need your help :'(

**Comment by ghost** [comment]
I'll build it and publish it again, link incoming.

**Comment by joseph619** [comment]
@ilwaz Will Exhentai work as well?

**Comment by Scrxtchy** [comment]
Exh should be working fine.
Favourites syncing is also fixed
still having issues with some thumbnails, I know what's causing it to not work, but I don't know what's causing the data to break 
_(DOM Parsing to find the image, but sometimes the image doesn't exist in the request)_

**Comment by ghost** [comment]
Released with @Scrxtchy's recent fixes for favorites: https://github.com/ilwaz/TachiyomiEH/releases/tag/v7.4.6-EH

**Comment by joseph619** [comment]
Can't restore backup, stuck at 0%

![0-02-01-0a44776545ef00f8e81c83489fbcc2f5d7966b389a93142274ef1fad0eb2537b_fe3633c5](https://user-images.githubusercontent.com/34897862/54875068-fe348500-4dcd-11e9-9241-f76ee32c244f.jpg)

Can't browse Ehentai, says 'Index: 1, Size: 1'

![0-02-01-6be44c8bd40085a9024abfb0c8d8ca96c860c54a46381dfb629892f7702198d8_bdcce5d8](https://user-images.githubusercontent.com/34897862/54875117-bc580e80-4dce-11e9-8314-5fb37bc63951.jpg)

Exhentai appears to work however

**Comment by ghost** [comment]
Ah, I know the problem. Fix incoming

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/54875316-e4885180-4e50-11e9-9084-78fabadbbe15.png)
Incoming

**Comment by joseph619** [comment]
@ilwaz @Scrxtchy This fork has Nhentai working for Tachiyomi, check it out

https://github.com/az4521/Tachiyomi/blob/4838e86e8a0490f2b5956a0a94b8557fdcd8584c/app/src/main/java/eu/kanade/tachiyomi/source/online/all/NHentai.kt

**Comment by Scrxtchy** [comment]
Thumbnail Fix. broken thumbnails remain broken until a cache clear I suppose
https://github.com/ilwaz/TachiyomiEH/pull/2

**Comment by Scrxtchy** [comment]
@joseph619 I'd rather probably just updating whatever we need to get `tachiyomi-extensions` properly working, as there is already team working on it
https://github.com/inorichi/tachiyomi-extensions/tree/master/src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai

This currently works in the regular tachiyomi versions, it just 404's for us

**Comment by joseph619** [comment]
@Scrxtchy: Are you going to remove Nhentai from this version, since there is already a working extension?

**Comment by Scrxtchy** [comment]
That's an option, I have already disabled hitomi.la due to it causing a critical crash, but I haven't done the same with nhentai as it wasn't much of an issue

**Comment by ghost** [comment]
Cut a new release with the thumbnail and ehentai browse fixes: https://github.com/ilwaz/TachiyomiEH/releases/tag/v7.4.7-EH

**Comment by joseph619** [comment]
I still see Hitomi under Settings

![0-02-01-ebc98701c1725ef19524fd014c1473706ce09eac796bce846d5bf3436ef6cbb0_161bcf45](https://user-images.githubusercontent.com/34897862/54875823-21fec780-4ddc-11e9-9652-c2a17eabac95.jpg)

**Comment by Scrxtchy** [comment]
> I still see Hitomi under Settings

Yes, but it is just removed from the source manager, so it cannot be used in galleries

https://github.com/Scrxtchy/TachiyomiEH/commit/dabf47b121c77a0769db6d7f4e6cde38db69df54

**Comment by joseph619** [comment]
@Scrxtchy Understood

Thumbnails in browse still don't load automatically, have to click on each title to load them

![0-02-01-609aa9d0532c95740ce9c367928ddc64538880abaf8cf38ccf43d58318cf97d6_1f1e470e](https://user-images.githubusercontent.com/34897862/54875891-5626b800-4ddd-11e9-8749-df9e7f293ef6.jpg)

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/54875921-84e37380-4e5b-11e9-87ea-1144d2c6cf88.png)

![image](https://user-images.githubusercontent.com/12771982/54875925-8e6cdb80-4e5b-11e9-99c2-015bca7af7e5.png)

**Comment by Scrxtchy** [comment]
OH FOR FUCK SAKE
I changed the wrong selector when dealing with @ilwaz's code review

https://github.com/ilwaz/TachiyomiEH/pull/2/files#diff-38623e27ff84b67842f6dafccd22ab42R78

it got past the both of us

**Comment by joseph619** [comment]
Edit: Nvm, backup seems to be working!

**Comment by kadaikhan** [comment]
@joseph619 if in your backup there is exhentai favs and you haven't log from the app in then it would not be able to load them.

**Comment by ghost** [comment]
@Scrxtchy fixed the thumbnails issues: https://github.com/ilwaz/TachiyomiEH/releases/tag/v7.4.8-EH

**Comment by joseph619** [comment]
@ilwaz Can't change thumbnails for local manga

**Comment by Scrxtchy** [comment]
> 
> 
> @ilwaz Can't change thumbnails for local manga

I did not have a problem, I just had to reopen the application for it to take affect

**Comment by joseph619** [comment]
> > @ilwaz Can't change thumbnails for local manga
> 
> I did not have a problem, I just had to reopen the application for it to take affect

Nope, still doesn't work. Not sure why.

**Comment by Solipso** [comment]
@joseph619 There was an issue like this before.

Try adding space in the end of folder of your local manga in /local/.

I mean change /local/example/ch1/ to /local/example /ch1/.

EDIT: This version actually doesn't need that space. Works fine even without it here.

**Comment by Zero777X** [comment]
Kissmanga is not working. SyntaxError: parse error (line 1)

**Comment by ghost** [comment]
@joseph619 @Zero777X this issue is to track the errors related to the e-hentai redesign, it would be easier to track those problems if you create a new issue (I guess in https://github.com/ilwaz/TachiyomiEH/ since this fork doesn't seem maintained)

**Comment by vannessqn** [comment]
isn't there is a well made e(x)-hentai app https://github.com/seven332/EhViewer?

**Comment by Solipso** [comment]
@vannessqn There is... but I personally prefer this one due to its reader, style, and, mainly, multiple sources

**Comment by eagle540** [comment]
Just downloaded the update to the app and it works perfectly fine on like I'm accessing ehentai right now thanks to everyone you folks are amazing

**Comment by Yandols** [comment]
Can anyone confirm that favorites sync is working in the @ilwaz fork? I saw a comment in the earlier part of the thread that they had their favorites removed when syncing.

**Comment by Scrxtchy** [comment]
It works, I fixed it

**Comment by Yandols** [comment]
Thanks for confirming! I didn't want my favorites library to get thanos snapped.

**Comment by CynicalRaven** [comment]
i read everything here from the start and i think it's beautiful how you guys are cooperating to bring back the app, thanks !

**Comment by Yandols** [comment]
Restoring nearly 3000 favourites from backup is taking ages. Is there a way to use or move the existing library from the old app directly into the new one?

Additionally, I get a lot of `Did not find balanced marker at 'alt=Representative image'` and `Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference` errors. I have no idea how to go about that.

**Comment by Scrxtchy** [comment]
I'm not entierly sure how the backup/restore feature functions.
Looks like every time we add a new entry back into the new database, we check against the website for any data if it's not already stored within the app's database.

The only other way this would be faster is if we were installing versions of the app that were the same as you had installed, like off F-Droid or whatever.
Ilwaz has been handling the build scripts because quite frankly I'm not even skilled at doing so.
If you were able to install a newer version as an update to the one you had installed, the database would be preserved, and you will not need to restore the backup

**Comment by Yandols** [comment]
I've been using the github version of the NerdNumber9 fork before the redesign happened. I thought that the one you and Ilwaz worked on would be an update to replace it but it instead installs itself as a new app so everything is blank on it after I installed it while the old app is still intact.

**Comment by ghost** [comment]
Unfortunately, I do not have the signing key that NerdNumber9 used to build and sign TachiyomiEH. This means I have to use a new key and our releases can not be seen by Android as an update to the previously installed app (I also changed the package name so instead of being forced to uninstall the old version, you can have them side by side).

@Yandols, please make an issue [here](https://github.com/ilwaz/TachiyomiEH/issues) about the restoring from backup error messages. There may be a couple things we can try to do with speeding up restoring from backup in general (maybe instantly displaying all of the favorites, but in a background thread fetching all the information instead of making the user wait).

**Comment by Zero777X** [comment]
How does one fix Kissmanga for TachiyomiEH?

**Comment by Solipso** [comment]
@Zero777X Considering all commits done in Tachiyomi, fixing Kissmanga would mean merging commits from tachiyomi dev (and they are currently still working on it even now) as well as making sure that merged commits dont conflict with this fork. (And @ilwaz said that the merges do cause conflicts.)

Currently it would be easier to use normal Tachiyomi by Inorichi. At least until all local sources are working (at least somehow).

You could make an issue [here](https://github.com/ilwaz/TachiyomiEH/issues), but it would be a part of [this](https://github.com/ilwaz/TachiyomiEH/issues/6) issue.

**Comment by dundandien** [comment]
It seem like the thumbnail picture in brows is broken again. Some was able to load but most was not.

**Comment by Scrxtchy** [comment]
> 
> 
> It seem like the thumbnail picture in brows is broken again. Some was able to load but most was not.

yup, also noticing this

**Comment by Scrxtchy** [comment]
They have changed the thumbnail functions again...
```
<div>
	<img style="height:348px;width:250px;top:-4px" alt="(C95) [From nuts (Garana)] Producer-san Otsukaresama desu (THE IDOLM@STER CINDERELLA GIRLS)" title="(C95) [From nuts (Garana)] Producer-san Otsukaresama desu (THE IDOLM@STER CINDERELLA GIRLS)" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://exhentai.org/t/06/b7/06b72d375bede8f4eddd3945d5fc30e78aab978c-224061-1200-1669-jpg_250.jpg" />
</div>
```
**Edit**
4 minutes later; this is actually a good change
I've already written a patch that should work

**Comment by Scrxtchy** [comment]
@dundandien 
https://github.com/ilwaz/TachiyomiEH/issues/20 👉 https://github.com/ilwaz/TachiyomiEH/pull/21

**Comment by NerdNumber9** [comment]
Fixed in latest release.

**Comment by Scrxtchy** [comment]
Welcome back! 🎉

**Comment by Zero777X** [comment]
Welcome Back! 🎉 Great app and thanks for returning to fix it!

**Comment by joseph619** [comment]
Welcome back man! Thanks for the new update 🎉

**Comment by TheBaddest** [comment]
sorry to necropost but I still can't access EH and EX, even after TachiyomiEH update v8.2.0-EH and updated all the extensions. 'Latest' just returns a blank page and 'Browse' returns "no results found".

**Comment by joseph619** [comment]
> sorry to necropost but I still can't access EH and EX, even after TachiyomiEH update v8.2.0-EH and updated all the extensions. 'Latest' just returns a blank page and 'Browse' returns "no results found".

Post a screenshot please, Eh and Ex works fine for me

**Comment by TheBaddest** [comment]
After clearing cache and cookies EH and EX works fine again. Sorry for the necropost for such a trivial matter.
________________________________

**Comment by yalopov** [comment]
Thanks for your work guys!
