### ISSUE TITLE
can't login e-hentai on app

### ISSUE THREAD

**Issue by maxdesu** [NerdNumber9/TachiyomiEH#6]
Hello, Deveoper

I have problem with login page on app. I download apk from e-hentai forum and install and tried to login but I can't login into e-hentai system. So its's bug? if not how to fix? See photo

![http://www.mx7.com/view2/AaVY3ENocnrOPnef](http://www.mx7.com/i/26a/F7MLLM.png)

Version: v6.1.4-EH
Android 4.1.2

**Comment by NerdNumber9** [comment]
From what I can tell, it seems as if your phone is too old. Sorry :(.
