### ISSUE TITLE
Kissmanga is down again. Error: com.squareup.duktape.DuktapException: SyntaxError Invalid Return (line 1)

### ISSUE THREAD

**Issue by Zero777X** [NerdNumber9/TachiyomiEH#63]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by NerdNumber9** [comment]
I'm well aware of all the duktape/cloudflare issues that are occurring with sources lately. Unfortunately, I don't have time to do another release right now. Expect the next release (along with a fix for this) by the middle/end of the next week.

**Comment by Zero777X** [comment]
Sure. Take your time. No rush. You have other priorities. We can wait.

**Comment by vicho1820** [comment]
The new tachiyomi update, fixed this problem. We can use tachiyomi in the meantime

**Comment by NerdNumber9** [comment]
Fixed in latest release.
