### ISSUE TITLE
Can't find HENTAI CAFE 

### ISSUE THREAD

**Issue by waqar1231** [NerdNumber9/TachiyomiEH#65]
Error :- 
Could not find this gallery
Could not find EH source

v8.2.0-EH

Android ver. 8.1.0 

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.Open TachiyomiEH app
 2.Go to galleries and go to settings 
 3. Can't find it in English(where it's use to be)

**Other details:**
Error occurred when I try to open it with Google and click on website ... Options appear to open it with TachiyomiEH or uc and i click on TachiyomiEH app

**Comment by NerdNumber9** [comment]
Install it from the Extensions section.

**Comment by waqar1231** [comment]
Sorry for that but Please tell the name of extension i can't seem to find it (extension for HENTAI CAFE) . It would be big help and I appreciate your work on this app .. thanks 

Edit :- 
Sorry I found that  it was a foolslide  extension and there is large number for other site too ..   I thank you again for your good work
