### ISSUE TITLE
ExHentai Favorites Syncing Issue

### ISSUE THREAD

**Issue by timetravel-1024** [NerdNumber9/TachiyomiEH#66]
**App version:**

v8.2.0-EH

**Android version:**

9

**Issue/Request:**

Despite having only used this app for my ExHentai account and not going on the actual website, after a few favorite syncs the app claims it is retrieving a single gallery from the remote library and does not continue. Since it does not get to the point where it uploads changes from the local library, I cannot upload any changes to my favorites made within the app until I perform the process in "Other Details" below.

**Steps to reproduce (if applicable)**

 1. Sync a couple of times.
 2. After a few syncs, the issue will occur.

**Other details:**

I can temporarily fix the issue by doing the following:
1. Backup my library.
2. Clear the app's storage.
3. Re-login to my ExHentai account.
4. Perform an initial favorites sync.
5. Recover the backup from Step 1.
6. Sync again to upload changes to my favorites since the last successful sync.

- After another sync or 2 the issue will happen again, causing me to have to repeat the above process.
- Enabling "Ignore sync errors when possible" setting does not fix the issue.

**Comment by NerdNumber9** [comment]
I'm aware of this issue and have already fixed it in the code, I just haven't had the chance to make a new release yet. The release is nearly finished though so expect an update soon!

**Comment by colpocleisis** [comment]
I have this issue only when I browse a gallery from the APP and then save the browsed gallery favorite from sadpanda website and then try to sync.

Solvable by clearing the database in advanced settings

**Comment by NerdNumber9** [comment]
Fixed in latest release.
