### ISSUE TITLE
App crashing when loading library updates.

### ISSUE THREAD

**Issue by Zero777X** [NerdNumber9/TachiyomiEH#67]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

**For all other requests Please fill out the form below and remove the first 3 lines of this template**

**App version:**

**Android version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by NerdNumber9** [comment]
I've found the issue. Fix will be released shortly, sorry!

**Comment by Zero777X** [comment]
It is okay thanks. Apologies, but EXHentai titles are also not loading.

**Comment by joseph619** [comment]
> It is okay thanks. Apologies, but EXHentai titles are also not loading.

That will also be fixed in next release, hopefully!

**Comment by NerdNumber9** [comment]
Fixed in latest release.
