### ISSUE TITLE
All sources unable to load images and chapters. Library and favourites included.

### ISSUE THREAD

**Issue by ghost** [NerdNumber9/TachiyomiEH#70]
**App version:**
V8.4.0-EH
**Android version:**
9
**Issue/Request:**
Upon opening a manga, no image loaded. Retry available but does not work. Tried clearing cache and reinstalling app, does not work. Went to favourites and library, same issue

**Comment by NerdNumber9** [comment]
Yeah, the latest release is a little unstable. A release that will fix all the bugs will be out in a couple of hours.

**Comment by NerdNumber9** [comment]
Fixed in latest release.
