### ISSUE TITLE
Local Media Will Not Be Loaded

### ISSUE THREAD

**Issue by jay-a-bhatt** [NerdNumber9/TachiyomiEH#88]
App Version v8.4.1

Android 9.0 Pie

**Issue/Request:**
Local media files (.cbz files) will not be recognized by TachiyomiEH. These files are not from any of the extension sources, but were put there by me. I have them in a external MicroSD card in /storage/4015-13EB/Tachiyomi/Local/ 

The normal Tachiyomi app does not have any problems recognizing the files. I do have the storage permission granted, so that's not the problem.

**Comment by fighuass** [comment]
I'm having the same problem.

**Comment by fsktom** [comment]
I'm also experiencing this problem.

**Comment by NerdNumber9** [comment]
Please make sure the media is saved in *Tachiyomi**EH**/local*, not *Tachiyomi/local*. Please re-open this issue if that does not solve the issue.
