### ISSUE TITLE
Hitomi.la "Failed handshake"

### ISSUE THREAD

**Issue by fam007e** [NerdNumber9/TachiyomiEH#89]
Hitomi.la fork for latest tachiyomiEH is not working... It shows " Handshake failed". In extension menu, it doesn't show either. Also tsumino is absent from extension options.
I've used 8.7 version to 7.2 all of them (tachEH)...
My Android device is Xiaomi Redmi Note 4X (Android 7.0). Please solve this issue...
Thank you

**Comment by Solipso** [comment]
Hitomi.la works fine for me. "Handshake failed" most likely means thar your provider is blocking you from connecting to hitomi.

To chech whether its true you can either open Hitomi.la in your mobile browser or try to open the source in webview. If the site doesn't load or you are shown your ISP/Government block page - problem on your end, VPN/Proxy are your friends.

Tsumino is source exclusive to TachiyomiEH and was added before Tachiyomi by Inorichi changed to "every source is extension". As such Tsumino should NOT appear in extensions until someone creates it as such (it's not at the moment of me writing this). To switch on or off the source you should go to your "Catalouges" menu and press gear button on top.

**Comment by fam007e** [comment]
I can view hitomi.la in webpage view mode.

**Comment by fam007e** [comment]
Handshake failed only appears in normal viewing mode of tachiyomiEH

**Comment by NerdNumber9** [comment]
@fam007e What device are you using? And what version of Android is your device using? Do you live in a country known for internet censorship?

**Comment by chaoticchoas** [comment]
I am having the same error when trying to access hitomi. I live in the us and can access the website normally from  the browser on my android 7.0

**Comment by NerdNumber9** [comment]
Looks like this is what's causing it: https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0

Basically, Google royally fucked up. I'll see if I can work around it in the upcoming release.

**Comment by fam007e** [comment]
@NerdNumber9 I have Xiaomi Redmi Note 4X handset and its Android version is 7.0. And I am from Bangladesh bt that's not the problem I've faced similar problems with VPNs...

**Comment by NerdNumber9** [comment]
Should be fixed in latest release
