### ISSUE TITLE
Tsumino captcha

### ISSUE THREAD

**Issue by Solipso** [NerdNumber9/TachiyomiEH#9]
Sometimes when I try to open chapter in Tsumino in app, i get error 404.

So, when I open Tsumino in browser, i get Captcha page just after i press "Read Online".

Well, i guess i am asking to implement captcha bypass/integrate internal browser so we could do it in the app.

**Comment by NerdNumber9** [comment]
I will look into this but it seems like it's going to be a lot of work so I can't promise anything...

**Comment by Solipso** [comment]
Oh! Thank you for noticing me!

Actually, second method is already here (though I just realised it). I mean that you can go to Tsumino description page already if you go to top-right menu button on manga info page.

It is far less annoying to do that (comparing to opening an actual browser or changing IP), but it still took me about 2 weeks to realise that, so if creating Captha bypass method is too problematic, I would suggest creating some sort of notification about opening Tsumino Site through the "Open in Browser" button when you use Tsumino Source.

**Comment by NerdNumber9** [comment]
Tsumino will now automatically show the captcha when necessary in the latest release.

**Comment by 90e75c80dd** [comment]
I don't know if this feature works for everyone else other than me, but I am just getting a toast message saying "2 exceptions occurred" instead of a capture. If I am opening the page in a browser I am getting a captcha and after solving it I am able to use Tsumino in the app again.
