### ISSUE TITLE
How do I get local media to work?

### ISSUE THREAD

**Issue by fighuass** [NerdNumber9/TachiyomiEH#90]
It doesn't work at all for me, I've tried the following approaches:

/TachiyomiEH/DoujinName.cbz
/TachiyomiEH/DoujinName/DoujinName.cbz
/TachiyomiEH/DoujinName/DoujinName/DoujinName.cbz
/TachiyomiEH/DoujinName/Chapter/DoujinName.cbz

Also, how are they supposed to be stored alongside in-app downloaded doujin/manga?

**Comment by null-dev** [comment]
You need to put them in: `/TachiyomiEH/local/DoujinName/ChapterName.cbz`

Once you have done that, you should be able to find them in `Galleries > Local manga`

**Comment by fighuass** [comment]
Thanks, that did the trick!
